# Database schema with timestamp columns

# --- !Ups

-- apply changes
create table equipment (
  id                            bigint generated by default as identity not null,
  created_at                    timestamp default current_timestamp not null,
  updated_at                    timestamp default current_timestamp not null,
  name                          varchar(255),
  purchase_price                decimal(16,3),
  description                   varchar(255),
  category                      varchar(21),
  constraint ck_equipment_category check ( category in ('SINGLE_BOARD_COMPUTER','SENSORS','MICROCONTROLLER','DEVELOPMENT_BOARD','CABLES','TOOLS','POWER_SUPPLY','STORAGE','OTHER')),
  constraint pk_equipment primary key (id)
);

create table equipment_reservation (
  id                            bigint generated by default as identity not null,
  created_at                    timestamp default current_timestamp not null,
  updated_at                    timestamp default current_timestamp not null,
  equipment_id                  bigint not null,
  user_id                       bigint not null,
  reservation_date              date,
  status                        varchar(9),
  constraint ck_equipment_reservation_status check ( status in ('ACTIVE','CANCELLED')),
  constraint pk_equipment_reservation primary key (id)
);

create table app_user (
  id                            bigint generated by default as identity not null,
  created_at                    timestamp default current_timestamp not null,
  updated_at                    timestamp default current_timestamp not null,
  username                      varchar(255),
  email                         varchar(255),
  password                      varchar(255),
  role                          varchar(8),
  constraint ck_app_user_role check ( role in ('ADMIN','STAFF','CUSTOMER')),
  constraint pk_app_user primary key (id)
);

-- foreign keys and indices
create index ix_equipment_reservation_equipment_id on equipment_reservation (equipment_id);
alter table equipment_reservation add constraint fk_equipment_reservation_equipment_id foreign key (equipment_id) references equipment (id) on delete restrict on update restrict;

create index ix_equipment_reservation_user_id on equipment_reservation (user_id);
alter table equipment_reservation add constraint fk_equipment_reservation_user_id foreign key (user_id) references app_user (id) on delete restrict on update restrict;


# --- !Downs

-- drop all foreign keys
alter table equipment_reservation drop constraint if exists fk_equipment_reservation_equipment_id;
drop index if exists ix_equipment_reservation_equipment_id;

alter table equipment_reservation drop constraint if exists fk_equipment_reservation_user_id;
drop index if exists ix_equipment_reservation_user_id;

-- drop all
drop table if exists equipment;

drop table if exists equipment_reservation;

drop table if exists app_user;

