-- Created by Ebean DDL
-- To stop Ebean DDL generation, remove this comment (both lines) and start using Evolutions

-- !Ups

-- apply changes
create table app_user (
  id                            bigint generated by default as identity not null,
  username                      varchar(255),
  email                         varchar(255),
  password                      varchar(255),
  constraint pk_app_user primary key (id)
);


-- !Downs

-- drop all
drop table if exists app_user;

