# Equipment management tables

# --- !Ups

create table equipment (
  id                            bigint generated by default as identity not null,
  name                          varchar(255),
  purchase_price                decimal(10,2),
  description                   varchar(1000),
  category                      varchar(50),
  constraint ck_equipment_category check ( category in ('SINGLE_BOARD_COMPUTER','SENSORS','MICROCONTROLLER','DEVELOPMENT_BOARD','CABLES','TOOLS','POWER_SUPPLY','STORAGE','OTHER')),
  constraint pk_equipment primary key (id)
);

create table equipment_reservation (
  id                            bigint generated by default as identity not null,
  equipment_id                  bigint not null,
  user_id                       bigint not null,
  reservation_date              date,
  status                        varchar(20),
  constraint ck_equipment_reservation_status check ( status in ('ACTIVE','CANCELLED')),
  constraint pk_equipment_reservation primary key (id)
);

alter table equipment_reservation add constraint fk_equipment_reservation_equipment_id foreign key (equipment_id) references equipment (id) on delete restrict on update restrict;
alter table equipment_reservation add constraint fk_equipment_reservation_user_id foreign key (user_id) references app_user (id) on delete restrict on update restrict;

create index ix_equipment_reservation_equipment_id on equipment_reservation (equipment_id);
create index ix_equipment_reservation_user_id on equipment_reservation (user_id);
create index ix_equipment_reservation_date on equipment_reservation (reservation_date);
create index ix_equipment_reservation_status on equipment_reservation (status);

# --- !Downs

drop table if exists equipment_reservation;
drop table if exists equipment;