# Add password reset token table

# --- !Ups

create table password_reset_token (
  id                            bigint generated by default as identity not null,
  created_at                    timestamp default current_timestamp not null,
  updated_at                    timestamp default current_timestamp not null,
  token                         varchar(255) not null,
  user_id                       bigint not null,
  expires_at                    timestamp not null,
  used                          boolean default false not null,
  constraint pk_password_reset_token primary key (id)
);

-- foreign keys and indices
create index ix_password_reset_token_user_id on password_reset_token (user_id);
alter table password_reset_token add constraint fk_password_reset_token_user_id foreign key (user_id) references app_user (id) on delete cascade on update restrict;

create index ix_password_reset_token_token on password_reset_token (token);
create index ix_password_reset_token_expires_at on password_reset_token (expires_at);

# --- !Downs

-- drop foreign keys and indices
alter table password_reset_token drop constraint if exists fk_password_reset_token_user_id;
drop index if exists ix_password_reset_token_user_id;
drop index if exists ix_password_reset_token_token;
drop index if exists ix_password_reset_token_expires_at;

-- drop table
drop table if exists password_reset_token;